<a href="https://colab.research.google.com/github/ikwak2/prac_class/blob/main/notebook/PythonPractice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Python Practice 

## Chapter 2
[Jump to Python Ch2](https://wikidocs.net/11)

### Numeric operations
  - Four fundamental arithmatic orperations(+, -, /, *)
  - power(**)
  - Quotiant and Remainder (%, //)  


In [ ]:
1 + 1 

2

In [ ]:
3 - 2

1

In [ ]:
3/2

1.5

In [ ]:
3*2

6

In [ ]:
3**2

9

In [ ]:
3%2

1

In [ ]:
3//2

1

### String operations
  - How to define string("0", '0', """0""", and '''0''')
  - Escape codes
  - string operations(+,*)
  - Indexing
  - formating 
  - string functions(join, split, upper, lower, strip, ...)


In [ ]:
str1 = "this is a string"

In [ ]:
str1 = """a man talked "hi jain". 'dfdf' in \n \t fdfd  """

In [ ]:
print(str1)

a man talked "hi jain". 'dfdf' in 
 	 fdfd  


In [ ]:
str = "aab" 
strB = "ccd"

In [ ]:
str+strB

'aabccd'

In [ ]:
str*3

'aabaabaab'

In [ ]:
str = "aabccd" 


In [ ]:
str[1:3]

'ab'

In [ ]:
a = "40"

"varible A: {}".format(a)

'varible A: 40'

In [ ]:
print( "varible A: {}".format(a) )

varible A: 40


In [ ]:
alist = ["a","b","c"]
alist

['a', 'b', 'c']

In [ ]:
b = " ".join(alist)
b

'a b c'

In [ ]:
b.split()

['a', 'b', 'c']

In [ ]:
b.upper().

'A B C'

In [ ]:
c = "a,b,c"

c.split(',')

['a', 'b', 'c']

### List 
  - How to define a list
  - Indexing
  - List operations (+, *, len )
  - Some functions with list (append, sort, reverse, ...)

In [ ]:
a = [1,2,3,4,0,-1]
a

[1, 2, 3, 4, 0, -1]

In [ ]:
b = [1,2, "ab", 4]
b

[1, 2, 'ab', 4]

In [ ]:
c = [1,2,[1,2], [1,2,[1,2,3]]]
c

[1, 2, [1, 2], [1, 2, [1, 2, 3]]]

In [ ]:
c[2][1]

2

In [ ]:
c[3][2][0]

1

In [ ]:
len(c)

4

In [ ]:
b+c

[1, 2, 'ab', 4, 1, 2, [1, 2], [1, 2, [1, 2, 3]]]

In [ ]:
b*3

[1, 2, 'ab', 4, 1, 2, 'ab', 4, 1, 2, 'ab', 4]

In [ ]:
a.sort()
a

[-1, 0, 1, 2, 3, 4]

In [ ]:
a.append(10)

In [ ]:
a

[-1, 0, 1, 2, 3, 4, 10]

In [ ]:
a.reverse()
a

[10, 4, 3, 2, 1, 0, -1]

### Dictionary
- How to define a dictionary
- functions(keys, values, items, get, in)

In [ ]:
dic = {'name':'pey', 'phone':'0119993323', 'birth': '1118'}

In [ ]:
dic

{'birth': '1118', 'name': 'pey', 'phone': '0119993323'}

In [ ]:
dic['birth']

'1118'

In [ ]:
dic['newkey1'] = 123

In [ ]:
dic

{'birth': '1118', 'name': 'pey', 'newkey1': 123, 'phone': '0119993323'}

In [ ]:
dic.items()

dict_items([('name', 'pey'), ('phone', '0119993323'), ('birth', '1118'), ('newkey1', 123)])

In [ ]:
for (key,value) in dic.items() : 
  print("key:{}, value:{}".format(key,value))


key:name, value:pey
key:phone, value:0119993323
key:birth, value:1118
key:newkey1, value:123


In [ ]:
dic.get('name')

'pey'

In [ ]:
dic['name']

'pey'

In [ ]:
dic.get('namename')

In [ ]:
dic['namename']

KeyError: ignored

In [ ]:
'name' in ['name', 'aaa']

True

### chapter 2 practice

1) Remove duplicates
``` python 
>>> a = [1, 1, 1, 2, 2, 3, 3, 3, 4, 4, 5]
```

2) How to extract 'A' and 'B' from the list 'a'?
``` python
>>> a = {'A':90, 'B':80, 'C':70}
```

3) What is the result? 
``` python
>>> a = b = [1, 2, 3]
>>> a[1] = 4
>>> print(b)
```

In [ ]:
a = [1, 1, 1, 2, 2, 3, 3, 3, 4, 4, 5]
list(set(a))

[1, 2, 3, 4, 5]

In [ ]:
a = {'A':90, 'B':80, 'C':70}

In [ ]:
a['A']

90

In [ ]:
a = b = [1, 2, 3]
a[1] = 4
print(b)

In [ ]:
a = [1, 2, 3]


In [ ]:
b = a

In [ ]:
a[1] = 4
a

[1, 4, 3]

In [ ]:
print(b)

[1, 4, 3]


In [ ]:
a = [1,2,3]

In [ ]:
b = a.copy()

In [ ]:
a[1] = 4
a

[1, 4, 3]

In [ ]:
print(b)

[1, 2, 3]


## Chapter 3

[Jump to python ch3](https://wikidocs.net/19)

### If else 


In [ ]:
if 1 :
  print("Do it")
else :
  print("cond not true")

Do it


In [ ]:
if 0 :
  print("Do it")
else :
  print("cond not true")

cond not true


In [ ]:
a = 10; b = 0

In [ ]:
if a > 0 :
  print("Do it")
else :
  print("cond not true")

Do it


In [ ]:
if a > 0 or b > 2 :
  print("Do it")
else :
  print("cond not true")

Do it


In [ ]:
name = 'Tom'; listofnames = ['Tom', 'Jane', 'Karl']

In [ ]:
if name not in listofnames :
  print("Do it")
else :
  print("cond not true")

cond not true


### For loop

In [ ]:
for i in range(5) :
  print(i)

0
1
2
3
4


In [ ]:
for name in listofnames :
  print(name)

Tom
Jane
Karl


In [ ]:
dic

{'birth': '1118', 'name': 'pey', 'newkey1': 123, 'phone': '0119993323'}

In [ ]:
for (key,value) in dic.items() :
  print(key, value)

name pey
phone 0119993323
birth 1118
newkey1 123


### Chapter 3, Practice 

1) Interprete the code below. What is the result?
``` python
a = "Life is too short, you need python"

if "wife" in a: print("wife")
elif "python" in a and "you" not in a: print("python")
elif "shirt" not in a: print("shirt")
elif "need" in a: print("need")
else: print("none")
```

In [ ]:
a = "Life is too short, you need python"
 
if "wife" in a: print("wife")
elif "python" in a and "you" not in a: print("python")
elif "shirt" not in a: print("shirt")
elif "need" in a: print("need")
else: print("none")

shirt


2) print numbers 1 to 100 using for loop

3) Do the same thing Using list compression 
``` python
numbers = [1, 2, 3, 4, 5]
result = []
for n in numbers:
    if n % 2 == 1:
        result.append(n*2)
```

In [ ]:
numbers = [1, 2, 3, 4, 5]
result = []
for n in numbers:
    if n % 2 == 1:
        result.append(n*2)

In [ ]:
result

[2, 6, 10]

In [ ]:
[ n*2  for n in numbers if n % 2 == 1 ]

[2, 6, 10]

In [ ]:
[ n*2 if n%2 ==1 else n*2+1 for n in numbers  ]

[2, 5, 6, 9, 10]

## Chapter 4 

[Jump to python ch4](https://wikidocs.net/26) 

### Function

In [ ]:
afunc <- function(a,b) {
    xdfdsfdsfd

    return (a+b)
}

In [ ]:
if 0 :
  print("hi")
  print("bye")
print("2")

2


In [ ]:
def add(a, b):
  return a+b




In [ ]:

print(add(3, 4))  

7


### File read and write

In [ ]:
with open('ids.txt', 'w') as f :
    f.write('ID\nJohn\nKarl\nAndy\nTim\n')


In [ ]:
with open('data1.txt', 'w') as f :
    f.write('ID\tfield1\tfield2\tfield3\nTom\t1\t3\t1\nJohn\t1\t3\t3\nTom\t1\t1\t1\nKarl\t1\t1\t2\nKarl\t1\t3\t2\nKarl\t2\t2\t2\nAndy\t1\t2\t3')


In [ ]:
with open('data2.txt', 'w') as f :
    f.write('ID\tfield1\tfield2\tfield3\nTom\t2\t3\t1\nJane\t1\t1\t3\nJane\t2\t2\t1\nMax\t3\t1\t2\nKarl\t1\t4\t2\nMax\t3\t2\t2\nMax\t2\t2\t1\nTom\t2\t3\t1\nJane\t1\t1\t3\nJane\t2\t2\t1\nMax\t3\t1\t2\nKarl\t1\t4\t2\nMax\t3\t2\t2\nMax\t2\t2\t1')


#### Read Data

In [ ]:
ids = []
with open('ids.txt', 'r') as f :
    for line in f :
#        print(line)
        ids.append(line.strip())


In [ ]:
ids

['ID', 'John', 'Karl', 'Andy', 'Tim']

In [ ]:
%%time

ids = []
V1s = []
with open('data1.txt', 'r', encoding='utf-8') as f :
    for item in f :
        print(item)
        ID, field1, _, _ = item.strip().split()
        ids.append(ID)
        V1s.append(field1)

ID	field1	field2	field3

Tom	1	3	1

John	1	3	3

Tom	1	1	1

Karl	1	1	2

Karl	1	3	2

Karl	2	2	2

Andy	1	2	3
CPU times: user 2.08 ms, sys: 0 ns, total: 2.08 ms
Wall time: 2.09 ms


In [ ]:
V1s

['field1', '1', '1', '1', '1', '1', '2', '1']

## Data Generator 

generator from data file

In [ ]:
import sys

In [ ]:
fnm = 'data2.txt'

In [ ]:
def fgenerator(fnm, iter_option = 0) :
    with open(fnm, 'r', encoding='utf-8') as f :
        for idx, item in enumerate(f) :
            ID, V1, V2, V3 = item.strip().split()
            if iter_option == 0 :
                yield ID
            elif iter_option == 1 :
                yield V1
            elif iter_option == 2 :
                yield V2
            else :
                yield V3


In [ ]:
gen_from_file = fgenerator(fnm)

In [ ]:
next(gen_from_file)

'Max'

In [ ]:
for i in gen_from_file :
  print(i)

ID
Tom
Jane
Jane
Max
Karl
Max
Max
Tom
Jane
Jane
Max
Karl
Max
Max


In [ ]:
sys.getsizeof(gen_from_file)

128

In [ ]:
def freader(fnm, iter_option = 0) :
    IDs = []
    with open(fnm, 'r', encoding='utf-8') as f :
        for idx, item in enumerate(f) :
            ID, V1, V2, V3 = item.strip().split()
            if iter_option == 0 :
                IDs.append(ID)
            elif iter_option == 1 :
                IDs.append(V1)
            elif iter_option == 2 :
                IDs.append(V2)
            else :
                IDs.append(V3)
    return IDs

In [ ]:
%%time
res = freader(fnm, 0)

CPU times: user 1.44 ms, sys: 43 µs, total: 1.48 ms
Wall time: 3.98 ms


In [ ]:
res

['ID',
 'Tom',
 'Jane',
 'Jane',
 'Max',
 'Karl',
 'Max',
 'Max',
 'Tom',
 'Jane',
 'Jane',
 'Max',
 'Karl',
 'Max',
 'Max']

In [ ]:
sys.getsizeof(res)

200

generator with class

In [ ]:
class DataGenerator() : 
    def __init__(self, fnm, iter_option=0) :
        self.fnm = fnm
        self.iter_option = iter_option
    
    def __iter__(self) :
        with open(fnm, 'r', encoding='utf-8') as f :
            for idx, item in enumerate(f) :
                ID, V1, V2, V3 = item.strip().split()
                if self.iter_option == 0 :
                    yield ID
                elif self.iter_option == 1 :
                    yield V1
                elif self.iter_option == 2 :
                    yield V2
                else :
                    yield V3
    
    def __len__(self) :
        with open(fnm, 'r', encoding='utf-8') as f :
            for idx, item in enumerate(f) :
                pass
            
            return idx
        

In [ ]:
fnm = 'data2.txt'

In [ ]:
gen1 = DataGenerator(fnm)

In [ ]:
len(gen1)

14

In [ ]:
for idx, item in enumerate(gen1) :
    print(item)

ID
Tom
Jane
Jane
Max
Karl
Max
Max
Tom
Jane
Jane
Max
Karl
Max
Max


## Numpy library

- NumPy stands for ‘Numerical Python’ or ‘Numeric Python’.

- Provides fast mathematical computation on arrays and matrices. 

In [ ]:
import numpy as np

In [ ]:
import numpy

### np.array()

In [ ]:

a = np.array([1,2,3,4,5,0])
b = [1,2,3,4,5]

differences?

In [ ]:
b + b

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [ ]:
a + a

array([ 2,  4,  6,  8, 10,  0])

In [ ]:
a * a  

array([ 1,  4,  9, 16, 25,  0])

In [ ]:
a

array([1, 2, 3, 4, 5, 0])

In [ ]:
a @ a

55

In [ ]:
a.shape

(6,)

#### Generating numpy arrays

- np.ones()
- np.zeros()
- np.arange()
- np.full()


In [ ]:
np.ones([2,3])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.zeros([2,2])

array([[0., 0.],
       [0., 0.]])

In [ ]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a = np.full([2,3], -1)
a

array([[-1, -1, -1],
       [-1, -1, -1]])

In [ ]:
a.T

array([[-1, -1],
       [-1, -1],
       [-1, -1]])

### Numpy array indexing



In [ ]:
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a[:3]

array([1, 2, 3])

In [ ]:
a[:-3]

array([1, 2, 3, 4, 5, 6])

In [ ]:
a[-3:]

array([7, 8, 9])

In [ ]:
a[2:5]

array([3, 4, 5])

In [ ]:
a[0:10:2]

array([1, 3, 5, 7, 9])

In [ ]:
b = np.arange(0,10).reshape(2,5)
b

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
b[:,2:]

array([[2, 3, 4],
       [7, 8, 9]])

### useful np functions

- np.abs()
- np.exp()
- np.pow()
- np.log()
- np.sqrt()


In [ ]:
a = np.arange(-3,5)
a

array([-3, -2, -1,  0,  1,  2,  3,  4])

In [ ]:
np.abs(a)


array([3, 2, 1, 0, 1, 2, 3, 4])

In [ ]:
np.exp(a)

array([4.97870684e-02, 1.35335283e-01, 3.67879441e-01, 1.00000000e+00,
       2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01])

In [ ]:
np.power(a,2)

array([ 9,  4,  1,  0,  1,  4,  9, 16])

In [ ]:
np.log( np.array([2,4,8]))

array([0.69314718, 1.38629436, 2.07944154])

In [ ]:
np.log2( np.array([2,4,8]))

array([1., 2., 3.])

if you want different base

In [ ]:
np.log( np.array([3,9]) ) / np.log(3)

array([1., 2.])

### Statistics 
[Statistics](https://numpy.org/doc/stable/reference/routines.statistics.html)

In [ ]:
a

array([-3, -2, -1,  0,  1,  2,  3,  4])

In [ ]:
np.mean(a)

0.5

In [ ]:
np.median(a)

0.5

In [ ]:
np.std(a)

2.29128784747792